apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: nimbus-aws
  namespace: argocd
spec:
  description: Nimbus workloads deployed by Argo CD on AWS.
  sourceRepos:
    - "*"
  destinations:
    - namespace: nimbus-aws-dev
      server: https://kubernetes.default.svc
    - namespace: nimbus-aws-stage
      server: https://kubernetes.default.svc
    - namespace: nimbus-aws-prod
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
