apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nimbus-azure-stage
resources:
  - ../../base
images:
  - name: nimbus-cloud-backend
    newName: <azure-acr-name>.azurecr.io/nimbus-cloud-backend
    newTag: "azure-stage-initial"
patchesStrategicMerge:
  - patch-configmap.yaml
  - patch-ingress.yaml
  - patch-rollout.yaml
  - patch-externalsecret.yaml
  - patch-hpa.yaml
