apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  labels:
    app.kubernetes.io/part-of: gitops-platform
spec:
  amiFamily: AL2023
  role: KarpenterNodeRole-placeholder
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: placeholder
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: placeholder
  amiSelectorTerms:
    - alias: al2023@latest
  tags:
    app.kubernetes.io/part-of: gitops-platform
