apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - root-application.yaml
  - gitops-settings.yaml
  - ../projects/nimbus-azure-project.yaml
  - ../applications/nimbus-azure-dev-app.yaml
  - ../applications/nimbus-azure-stage-app.yaml
  - ../applications/nimbus-azure-prod-app.yaml
replacements:
  - source:
      kind: ConfigMap
      name: gitops-settings
      fieldPath: data.repoURL
    targets:
      - select:
          kind: Application
        fieldPaths:
          - spec.source.repoURL
  - source:
      kind: ConfigMap
      name: gitops-settings
      fieldPath: data.revision
    targets:
      - select:
          kind: Application
        fieldPaths:
          - spec.source.targetRevision
