apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nimbus-platform
spec:
  selector:
    matchLabels:
      monitoring.nimbus.io/scrape: "true"
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
