apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: karpenter-settings
    envs:
      - karpenter-settings.env
generatorOptions:
  disableNameSuffixHash: true
replacements:
  - source:
      kind: ConfigMap
      name: karpenter-settings
      fieldPath: data.NODE_ROLE
    targets:
      - select:
          group: karpenter.k8s.aws
          version: v1
          kind: EC2NodeClass
          name: default
        fieldPaths:
          - spec.role
  - source:
      kind: ConfigMap
      name: karpenter-settings
      fieldPath: data.CLUSTER_NAME
    targets:
      - select:
          group: karpenter.k8s.aws
          version: v1
          kind: EC2NodeClass
          name: default
        fieldPaths:
          - spec.subnetSelectorTerms.0.tags.[karpenter.sh/discovery]
          - spec.securityGroupSelectorTerms.0.tags.[karpenter.sh/discovery]
