apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nimbus-platform
spec:
  data:
    - secretKey: NIMBUS_DATABASE_URL
      remoteRef:
        key: nimbus-azure-dev-runtime
        property: database_url
    - secretKey: NIMBUS_TOKEN_SECRET
      remoteRef:
        key: nimbus-azure-dev-runtime
        property: token_secret
